mylist = ["prashant", "Ashish", "Komal", "Ankush", "Sandip", 60.52, 30]
print(mylist)
print(type(mylist))
print(mylist[0])
print(mylist[1])
print(mylist[2])
print(mylist[3])
print(mylist[-1])
print(mylist[2:5])
print(mylist[:5])
mylist.append('harsh')
print(mylist)
mylist.append(100)
print(mylist)
